name: Terraform (Terragrunt)

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch: # ✅ allows manual runs (for apply)

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "0.88.0"
          tg_dir: "."
          tg_command: "hcl fmt --check --diff"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt Plan (all modules)
        run: terragrunt run-all plan | tee terragrunt-plan.log

      - name: Upload Plan Logs
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt-plan
          path: terragrunt-plan.log

  apply:
    needs: plan
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # ✅ manual only
    env:
      AWS_REGION: ap-south-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "0.88.0"
          tg_dir: "."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt Apply (all modules)
        run: terragrunt run-all apply -auto-approve
